' DIAGRAM #########################################
' RFC003 atomic swap
' #################################################
@startuml
' #################################################
' SETTINGS: color settings of diagram
' #################################################
skinparam sequence {
	BorderColor black
	ArrowColor black
	ActorBorderColor black
	LifeLineBorderColor black
	LifeLineBackgroundColor white
	
	ParticipantBorderColor black
	ParticipantBackgroundColor white
	ParticipantFontColor black
	
	ActorBackgroundColor white
	ActorFontColor black
}
' #################################################
' ACTORS
' #################################################
actor Alice
participant "Alice\nComit-Node" as AC
participant "Alpha\nLedger" as Alpha
participant "Beta\nLedger" as Beta
participant "Bob\nComit-Node" as BC
actor Bob

' allow parallelism
!pragma teoz true

' #################################################
' DIAGRAM
' #################################################
Alice->AC: send swap request
AC->AC: generate secret
AC->AC: hash secret
AC->BC: swap request 
note left #white
	swap request includes 
	- hash of secret 
	- expiries
	- Alice's identities (if relevant)
end note
BC->Bob: new swap request
Bob->BC: accept swap request
BC->Alpha: monitor funding of HTLC on Alpha
BC->AC: accept swap request
note left #white
	swap accept includes 
	- expiries
	- Bob's identities (if relevant)
end note
AC->Alpha: monitor funding of HTLC on Alpha
AC->Alice: fund action
Alice->AC: fund Alpha
AC->AC: prepare HTLC for Alpha
note left #white
	Both Alice and Bob have
	all the parameter to create
	the exactly same HTLC code.
end note
AC-->Alice: prepared TX
Alice->Alpha: TX to fund HTLC on Alpha
Alpha->Alpha: TX in new block
AC->Alpha: Alice's comit node notices\nfunded HTLC on Alpha
& BC->Alpha: Bob's comit node notices\nfunded HTLC on Alpha
AC->Beta: monitor funding of HTLC on Beta
& BC->Beta: monitor funding of HTLC on Beta
AC->Alice: refund available
& BC->Bob: fund available
Bob->BC: fund Beta
BC->BC: prepare Beta HTLC
BC-->Bob: prepared TX
note left #white
	Both Alice and Bob have
	all the parameter to create
	the exactly same HTLC code.
end note
Bob->Beta: TX to fund HTLC on Beta
Beta->Beta: TX in new block
BC->Beta: Bob's comit node notices\nfunded HTLC on Beta
& AC->Beta: Alice's comit node notices\nfunded HTLC on Beta
BC->Bob: refund available
& AC->Alice: redeem available
Alice->AC: redeem Beta
AC->AC: prepare redeem TX
note left #white
	Alice has to expose the
	secret to redeem.
end note
AC-->Alice: prepared TX
Alice->Beta: TX to redeem
note right #white
	HTLC hashes the
	given secret and matches
	it against the hash it has.
	Secret publicly available.
end note
Beta->Beta: TX in new block
note left #white
	Alice got Beta asset.
end note
AC->Beta: Alice's comit node notices\nredeemed HTLC on Beta
& BC->Beta: Bob's comit node notices\nredeemed HTLC on Beta
AC->Alice: just refund available
& BC->Bob: redeem available
note right #white
	Bob's comit node
	retrieves the secret.
end note
Bob->BC: redeem
BC->BC: prepare redeem TX
BC-->Bob: prepared TX
Bob->Alpha: TX to redeem
note left #white
	HTLC hashes the
	given secret and matches
	it against the hash it has.
end note
Alpha->Alpha: TX in new block
note right #white
	Bob got Alpha asset.
end note
AC->Alpha: Alice's comit node notices\nredeemed HTLC on Alpha
& BC->Alpha: Bob's comit node notices\nredeemed HTLC on Alpha
AC->Alice: swap complete
& BC->Bob: swap complete

@enduml