' DIAGRAM #########################################
' RFC003 atomic swap
' #################################################
@startuml
' #################################################
' SETTINGS: color settings of diagram
' #################################################
skinparam sequence {
	BorderColor black
	ArrowColor black
	ActorBorderColor black
	LifeLineBorderColor black
	LifeLineBackgroundColor white
	
	ParticipantBorderColor black
	ParticipantBackgroundColor white
	ParticipantFontColor black
	
	ActorBackgroundColor white
	ActorFontColor black
}
' #################################################
' ACTORS
' #################################################
actor Alice
participant "Alice\nComit-Node" as AC
participant "Bitcoin\nLedger" as Alpha
participant "Bob\nComit-Node" as BC
actor Bob

' allow parallelism
!pragma teoz true

' #################################################
' DIAGRAM
' #################################################
Alice->AC: send swap request
AC->AC: generate secret
AC->AC: hash secret
AC->AC: prepare refund identity
AC->BC: send swap request
note left #white
{
  "type": "SWAP",
  "headers": {
    "alpha_ledger": {
      "value": "bitcoin",
      "parameters": { "network": "mainnet" }
    },
    "beta_ledger": {...},
    "alpha_asset": {
      "value": "bitcoin",
      "parameters": { "quantity": "100000000" }
    },
    "beta_asset": {...},
    "protocol": {
        "value" : "comit-rfc-003",
        "parameters" : {
            "hash_function" : "SHA-256" }
    }
  },
  "body": {
    "alpha_ledger_refund_identity": "1925a...",
    "alpha_expiry": 1552,
    "secret_hash" : "1f69c...",
    ...
  },
}
end note
BC->Bob: new swap request
Bob->BC: accept swap request
BC->BC: prepare redeem identity
BC->AC: accept swap request
note right #white
{
  "type": "SWAP",
  "headers": {
    "alpha_ledger": {
      "value": "bitcoin",
      "parameters": { "network": "mainnet" }
    },
    "beta_ledger": {...},
    "alpha_asset": {
      "value": "bitcoin",
      "parameters": { "quantity": "100000000" }
    },
    "beta_asset": {...},
    "protocol": {
        "value" : "comit-rfc-003",
        "parameters" : { "hash_function" :
            "SHA-256" }
    }
  },
  "body": {
    "alpha_ledger_refund_identity": "1925a...",
    "alpha_expiry": 1552,
    "secret_hash" : "1f69c...",
    **"alpha_ledger_redeem_identity": "1925b...",**
    ...
  },
}
end note
BC->BC: compile contract_script
note left #white
OP_IF
    OP_SIZE 32 OP_EQUALVERIFY
    OP_SHA256 1f69c... OP_EQUALVERIFY
    OP_DUP OP_HASH160 1925b..
OP_ELSE
    1552 OP_CHECKLOCKTIMEVERIFY OP_DROP
    OP_DUP OP_HASH160 1925a..
OP_ENDIF
OP_EQUALVERIFY
OP_CHECKSIG
end note
& AC->AC: compile contract_script
note left #white
OP_IF
    OP_SIZE 32 OP_EQUALVERIFY
    OP_SHA256 1f69c... OP_EQUALVERIFY
    OP_DUP OP_HASH160 1925b..
OP_ELSE
    1552 OP_CHECKLOCKTIMEVERIFY OP_DROP
    OP_DUP OP_HASH160 1925a..
OP_ENDIF
OP_EQUALVERIFY
OP_CHECKSIG
end note
BC->Alpha: monitor deployment of HTLC on Bitcoin
& AC->Alpha: monitor deployment of HTLC on Bitcoin
note left #white
	Both Alice and Bob know all parameters.
	Bitcoin scripts are represented by a
	specially calculated bitcoin address.
	Thus, monitoring it just done by looking
	for this address in incoming new blocks.
end note
AC->Alice: fund action
Alice->AC: fund
AC->AC: prepare transaction with\n  contract_script,\n  100000000 sat
AC-->Alice: prepared TX
Alice->Alpha: send TX
Alpha->Alpha: TX in new block
AC->Alpha: Alice's comit node notices\nfunded HTLC on Alpha
& BC->Alpha: Bob's comit node notices\nfunded HTLC on Alpha

@enduml